version: '3'

services:
  node-build-monitor:
    restart: unless-stopped
    image: brunobernardnh/node-build-monitor
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000